
CREATE DATABASE CRMESC
GO
USE CRMESC
GO
CREATE TABLE USUARIOS(
	ID INT IDENTITY,
	USUARIO VARCHAR(30) NOT NULL UNIQUE,
	SENHA VARCHAR(12) NOT NULL,
	CONSTRAINT PKUSUARIOS PRIMARY KEY(ID)
)
GO
INSERT INTO USUARIOS VALUES('RAILANDER','12345')
GO
/*
INSERT INTO USUARIOS(UDUARIO, SENHA) VALUES('@LOGIN','@SENHA')
*/
GO

CREATE TABLE ALUNO(
	IDALUNO INT IDENTITY,--0
	NOME VARCHAR(50) NOT NULL, --1
	NASCIMENTO DATETIME NOT NULL,--2
	GENERO CHAR(1) NOT NULL, --3
	FOTO IMAGE NOT NULL,--4
	CONSTRAINT PKALUNO PRIMARY KEY(IDALUNO),
)
GO
/* INSERT INTO ALUNO (NOME, NASCIMENTO, GENERO, FOTO) VALUES(@NM, @NSC, @GNR, @ft) */

CREATE TABLE TELEFONE(
	IDTELEFONE INT IDENTITY, --0
	NUMERO VARCHAR(18) NOT NULL,--1
	CONSTRAINT PKTELEFONE PRIMARY KEY(IDTELEFONE)
)
GO
/* INSERT INTO TELEFONE (NUMERO) */

CREATE TABLE RESPONSAVEL(
	IDRESPONSAVEL INT IDENTITY,
	NOME VARCHAR(50) NOT NULL,
	IDALUNO INT NOT NULL,
	CONSTRAINT PKRESPONSAVEL PRIMARY KEY(IDRESPONSAVEL),
	CONSTRAINT FKALUNO_RESPONS FOREIGN KEY(IDALUNO) REFERENCES ALUNO(IDALUNO)
)
GO

select * from TELEFONE
CREATE TABLE RESPONSAVEL_TELEFONE(
	IDRESPONSAVEL INT NOT NULL,
	IDTELEFONE INT NOT NULL
	CONSTRAINT PKALUNOTELEFONE PRIMARY KEY(IDRESPONSAVEL, IDTELEFONE),
	CONSTRAINT FKRESP_RESPOTEL FOREIGN KEY(IDRESPONSAVEL) REFERENCES RESPONSAVEL(IDRESPONSAVEL),
	CONSTRAINT FKTELEFONE_ALUNTEL FOREIGN KEY(IDTELEFONE) REFERENCES TELEFONE(IDTELEFONE)
)
GO

/* INSERT INTO ALUNO_TELEFONE (IDALUNO, IDTELEFONE) VALUES(@IDAL, @IDTEL) */

CREATE TABLE ENDERECO(
	IDENDERECO INT NOT NULL IDENTITY,
	CEP VARCHAR(15),
	UF CHAR(2) NOT NULL,
	CIDADE VARCHAR(50) NOT NULL,
	BAIRRO  VARCHAR(50) NOT NULL,
	RUA VARCHAR(50),
	NUMERO INT,
	CONSTRAINT PKENDERECO PRIMARY KEY(IDENDERECO)
)
GO



/* INSERT INTO ENDERECO (CEP, UF, CIDADE, BAIRRO, RUA, NUMERO) VALUES(@CP, @UF, @CI, @BA, @RU, @NU) */

CREATE TABLE RESPONSAVEL_ENDERECO(
	IDENDERECO INT,
	IDRESPONSAVEL INT,
	CONSTRAINT PKRESPONSAVELENDERECO PRIMARY KEY(IDRESPONSAVEL, IDENDERECO),
	CONSTRAINT FKENDERECO_ALUEND FOREIGN KEY(IDENDERECO) REFERENCES ENDERECO(IDENDERECO),
	CONSTRAINT FT_RESPON_RESPOEND FOREIGN KEY(IDRESPONSAVEL) REFERENCES RESPONSAVEL(IDRESPONSAVEL)
)
GO

use master;
drop database crmesc

SELECT  A.IDALUNO, A.NOME, AE.IDENDERECO, AE.IDALUNO, E.IDENDERECO, E.CEP, E.CIDADE, E.RUA
FROM ALUNO A
INNER JOIN ALUNO_ENDERECO AE
ON A.IDALUNO = AE.IDALUNO
INNER JOIN ENDERECO E
ON AE.IDENDERECO = E.IDENDERECO


use master
drop database CRMESC


SELECT E.IDENDERECO, E.CEP, E.UF, E.CIDADE, E.BAIRRO, E.RUA, E.NUMERO FROM ENDERECO E
INNER JOIN ALUNO_ENDERECO AE
ON E.IDENDERECO = AE.IDENDERECO
INNER JOIN ALUNO A
ON AE.IDALUNO = A.IDALUNO



select * from ALUNO

SELECT R.IDRESPONSAVEL,R.NOME, R.IDALUNO FROM RESPONSAVEL R
                 INNER JOIN ALUNO A
                 ON A.IDALUNO = R.IDALUNO
                ORDER BY R.NOME