CREATE DATABASE CRMESC
GO
USE CRMESC
GO
CREATE TABLE USUARIOS(
	ID INT IDENTITY,
	USUARIO VARCHAR(30) NOT NULL UNIQUE,
	SENHA VARCHAR(12) NOT NULL,
	CONSTRAINT PKUSUARIOS PRIMARY KEY(ID)
)
GO
INSERT INTO USUARIOS VALUES('RAILANDER','12345')
GO
/*
INSERT INTO USUARIOS(UDUARIO, SENHA) VALUES('@LOGIN','@SENHA')
*/
GO

CREATE TABLE ALUNO(
	IDALUNO INT IDENTITY,--0
	NOME VARCHAR(50) NOT NULL, --1
	NASCIMENTO DATETIME NOT NULL,--2
	GENERO CHAR(1) NOT NULL, --3
	FOTO IMAGE NOT NULL,--4
	CONSTRAINT PKALUNO PRIMARY KEY(IDALUNO),
)
GO
/* INSERT INTO ALUNO (NOME, NASCIMENTO, GENERO, FOTO) VALUES(@NM, @NSC, @GNR, @ft) */

CREATE TABLE TELEFONE(
	IDTELEFONE INT IDENTITY, --0
	NUMERO VARCHAR(15) NOT NULL,--1
	CONSTRAINT PKTELEFONE PRIMARY KEY(IDTELEFONE)
)
GO
/* INSERT INTO TELEFONE (NUMERO) */

CREATE TABLE ALUNO_TELEFONE(
	IDALUNO INT NOT NULL,
	IDTELEFONE INT NOT NULL
	CONSTRAINT PKALUNOTELEFONE PRIMARY KEY(IDALUNO, IDTELEFONE),
	CONSTRAINT FKALUNO_ALUNTEL FOREIGN KEY(IDALUNO) REFERENCES ALUNO(IDALUNO),
	CONSTRAINT FKTELEFONE_ALUNTEL FOREIGN KEY(IDTELEFONE) REFERENCES TELEFONE(IDTELEFONE)
)
GO

/* INSERT INTO ALUNO_TELEFONE (IDALUNO, IDTELEFONE) VALUES(@IDAL, @IDTEL) */

CREATE TABLE ENDERECO(
	IDENDERECO INT NOT NULL IDENTITY,
	CEP VARCHAR(15),
	UF CHAR(2) NOT NULL,
	CIDADE VARCHAR(50) NOT NULL,
	BAIRRO  VARCHAR(50) NOT NULL,
	RUA VARCHAR(50),
	NUMERO INT,
	CONSTRAINT PKENDERECO PRIMARY KEY(IDENDERECO)
)
GO

/* INSERT INTO ENDERECO (CEP, UF, CIDADE, BAIRRO, RUA, NUMERO) VALUES(@CP, @UF, @CI, @BA, @RU, @NU) */

CREATE TABLE ALUNO_ENDERECO(
	IDENDERECO INT,
	IDALUNO INT,
	CONSTRAINT PKALUNOENDERECO PRIMARY KEY(IDALUNO, IDENDERECO),
	CONSTRAINT FKENDERECO_ALUEND FOREIGN KEY(IDENDERECO) REFERENCES ENDERECO(IDENDERECO),
	CONSTRAINT FKALUNO_ALUEND FOREIGN KEY(IDALUNO) REFERENCES ALUNO(IDALUNO)
)
GO

/* INSERT INTO ALUNO_ENDERECO (IDENDERECO, IDALUNO) VALUES (@IDEND, @IDAL) */

CREATE TABLE RESPONSAVEL(
	IDRESPONSAVEL INT IDENTITY,
	NOME VARCHAR(50) NOT NULL,
	IDALUNO INT NOT NULL,
	CONSTRAINT PKRESPONSAVEL PRIMARY KEY(IDRESPONSAVEL),
	CONSTRAINT FKALUNO_RESPONS FOREIGN KEY(IDALUNO) REFERENCES ALUNO(IDALUNO)
)
GO

/* INSERT INTO RESPONSAVEL (NOME, IDALUNO) VALUES (@NM,@IDAL)*/
