/*

CREATE TABLE USUARIOS(
	ID INT IDENTITY,
	USUARIO VARCHAR(30) NOT NULL UNIQUE,
	SENHA VARCHAR(12) NOT NULL,
	CONSTRAINT PKUSUARIOS PRIMARY KEY(ID)
);
*/
/*
CREATE TABLE ALUNO(
	ID INT IDENTITY,
	NOME VARCHAR(50) NOT NULL,
	NASCIMENTO DATETIME NOT NULL,
	GENERO VARCHAR(10) not null,
	TELEFONE VARCHAR(20),
	ENDERECO TEXT NOT NULL,
	foto image,
	CONSTRAINT PKALUNO PRIMARY KEY(ID)
)
*/

