CREATE DATABASE CRMESC
GO
USE CRMESC
GO
CREATE TABLE USUARIOS(
	ID INT IDENTITY,
	USUARIO VARCHAR(30) NOT NULL UNIQUE,
	SENHA VARCHAR(12) NOT NULL,
	CONSTRAINT PKUSUARIOS PRIMARY KEY(ID)
)
GO

INSERT INTO USUARIOS VALUES('RAILANDER','12345')
GO

CREATE TABLE ALUNO(
	ID INT IDENTITY,--0
	NOME VARCHAR(50) NOT NULL, --1
	NASCIMENTO DATETIME NOT NULL,--2
	GENERO VARCHAR(10) NOT NULL, --3
	TELEFONE VARCHAR(15) NOT NULL,--4
	foto image,--5
	CEP VARCHAR(15),--6
	RUA VARCHAR(50),--7
	BAIRRO VARCHAR(50),--8
	NUMERO INT,--9
	CIDADE VARCHAR(50) NOT NULL,--10
	UF VARCHAR(3) NOT NULL,--11
	CONSTRAINT PKALUNO PRIMARY KEY(ID)
)
GO


INSERT INTO ALUNO (NOME, NASCIMENTO, GERERO, TELEFONE, FOTO, CEP, RUA, BAIRRO, NUMERO, CIDADE,
UF) VALUES(@nm, @nsc, @gnr, @tel, @ft, @cp, @ru, @ba, @nu, @ci, @uf);
 
/*drop database CRMESC
SELECT  a.nome, * FROM ENDERECO e
inner join aluno a
on e.id = a.id;
*/
select * from ALUNO




